name: github-pages

on:
  push:
    branches: 
      - main
    paths:
      - Web/**
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0

    - name: Publish
      run: dotnet publish Web/Web.csproj -c Release -o release --nologo

    - name: Stop Jekyll
      run: touch release/wwwroot/.nojekyll
      
    - name: Commit to pages branch
      uses: JamesIves/github-pages-deploy-action@4.1.1
      with:
        branch: gh-pages
        folder: release/wwwroot
