name: azure-pit-wa-govee

on:
  push:
    branches:
      - main
    paths:
      - Web/**
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2
          include-prerelease: true

      - name: Build with dotnet
        run: dotnet build Web/Web.csproj --configuration Release

      - name: dotnet publish
        run: dotnet publish Web/Web.csproj -c Release -o ${{env.DOTNET_ROOT}}/myapp

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v2
          path: ${{env.DOTNET_ROOT}}/myapp

  deploy:
    runs-on: windows-latest
    needs: build
    environment:
      name: 'Production'
        with:
          app-name: 'pit-wa-govee'
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_E188C08172DE4EF9BFEF86DF072C4274 }}
          package: .
